version: '3'
services:
  # container for API
  api:
    extends:
      file: ./deployment/common.yaml
      service: api
    ports:
      - ${API_HTTP_PORT}:80
      - ${API_HTTPS_PORT}:443
  db:
    extends:
      file: ./deployment/common.yaml
      service: db
