version: '3'
services:
  # container for API
  app:
    extends:
      file: ./deployment/common.yaml
      service: app
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
  db:
    extends:
      file: ./deployment/common.yaml
      service: db
