version: '3'
services:
  # container for API
  traefik:
    image: ${DOCKER_IMAGE_TRAEFIK}
    ports:
      - ${TRAEFIK_HTTP_PORT}:80
      - ${TRAEFIK_HTTPS_PORT}:443
      - ${TRAEFIK_DASHBOARD_PORT}:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./deployment/certs:/certs:ro
      - ./deployment/traefik/traefik.yml:/traefik.yml:ro
      - ./deployment/traefik/tls.yml:/tls.yml:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.service=traefik
  api:
    extends:
      file: ./deployment/common.yaml
      service: api
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.traefik.entrypoints=http,https
      # URL to reach this container
      - "traefik.http.routers.api.rule=Host(`localhost`)"
      # Activation of TLS
      - "traefik.http.routers.api.tls=true"
  db:
    extends:
      file: ./deployment/common.yaml
      service: db
  pma:
    extends:
      file: ./deployment/common.yaml
      service: pma
    depends_on:
      - db