version: '3'
services:
  api:
    image: ${DOCKER_IMAGE_API}
    working_dir: /var/www/app
    volumes:
      - ../src:/var/www/app:delegated
      - ./conf/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./conf/queue.conf:/etc/supervisor/conf.d/queue.conf
      - ./conf/nginx.conf:/etc/nginx/sites-enabled/default.conf
  db:
    image: ${DOCKER_IMAGE_DB}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -proot"]
      interval: 10s
      timeout: 5s
      retries: 3
  # container for UI database management
  pma:
    image: ${DOCKER_IMAGE_PMA}
    ports:
      - ${PMA_PORT}:80
    environment:
      UPLOAD_LIMIT: ${PMA_UPLOAD_LIMIT}
      PMA_HOSTS: ${MYSQL_DATABASE}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}