name: Build
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Touch .env
        run: cp .env.dev .env
      - name: Up container
        run: docker-compose -f github-ci.yaml up -d
      - name: Install package
        run: docker-compose -f github-ci.yaml exec -T api composer install
      - name: generate key
        run: docker-compose -f github-ci.yaml -T api php artisan key:generate
      - name: Testing about migrate
        run: docker-compose -f github-ci.yaml -T api php artisan migrate
      - name: process linter
        run: docker-compose -f github-ci.yaml -T api composer lint
      - name: run unit test
        run: docker-compose -f github-ci.yaml -T api composer test
