name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Touch container .env
        run: cp .env.dev .env
      - name: Up container
        run: docker-compose -f github-ci.yaml up -d
      - name: Install package
        run: docker-compose -f github-ci.yaml exec -T api composer install
      - name: touch api .env
        run: docker-compose -f github-ci.yaml exec -T api cp .env.example .env
      - name: generate key
        run: docker-compose -f github-ci.yaml exec -T api php artisan key:generate
      - name: Testing about migrate
        run: docker-compose -f github-ci.yaml exec -T api php artisan migrate
      - name: process linter
        run: docker-compose -f github-ci.yaml exec -T api composer lint
      - name: run unit test
        run: docker-compose -f github-ci.yaml exec -T api vendor/bin/phpunit --coverage-clover coverage.xml
      - uses: actions/checkout@v2
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
            file: ./coverage.xml